name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        run: deno cache src/cli/jira.ts

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-env --allow-read --allow-write=./tmp --allow-run --unstable
