name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Devbox
        run: |
          curl -fsSL https://get.jetify.com/devbox | bash -s -- -f

      - name: Prepare Devbox environment
        run: devbox install

      - name: Format
        run: devbox run -- deno fmt --check

      - name: Lint
        run: devbox run -- deno lint

      - name: Test
        run: devbox run -- deno task test

      - name: Generate SPDX SBOM
        run: devbox run -- deno task sbom -- --output sbom.spdx.json

      - name: Submit dependency snapshot
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
        with:
          filePath: .
          filePattern: sbom.spdx.json
